### PR TITLE
Punches, kicks and Update 3 Super Sonic forms

### PR DESCRIPTION
**Pull request by H-A-M-G-E-R**

### CODE REVIEW

**Comment by RagdollClash** [comment]
I purposefully chose to not affect the punch and kick models because they're used just for the effects. Additionally, I don't think there's much of a reason to support the other 2 Super Sonic models given they're only present in pre-rendered cutscenes.

**Comment by H-A-M-G-E-R** [comment]
there's the realtime cutscenes mod

**Comment by H-A-M-G-E-R** [comment]
the kick effect always use the default sonic's shoe

**Comment by H-A-M-G-E-R** [comment]
so if you use the korone outfit the kicks should use korone shoes

**Comment by H-A-M-G-E-R** [comment]
realtime cutscenes mod actually doesn't include damaged super sonic

**Pull request closed without merging**
